# Generated by Django 5.1 on 2024-09-04 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='company_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='location',
            new_name='address',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
