# Generated by Django 5.0.7 on 2024-09-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_category_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
